language: go

go:
  - 1.8
  - 1.9
  - 1.10
  - tip

before_install:
  - go get github.com/mattn/goveralls

script:
  - go get -t ./...
  - go test -race ./...

after_script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
